import type { Step } from "./synth303";

export interface MidiPattern {
  id: string;
  title: string;
  file: string;
  bpm: number;
  range: string;
  pattern: Step[];
}

export const MIDI_PATTERNS: MidiPattern[] = [
  {
    id: "g-force-siren",
    title: "G-Force Siren",
    file: "01-g-force-siren.mid",
    bpm: 140,
    range: "G1-A#5",
    pattern: [
      { on: true, note: "G1", accent: false, slide: false },
      { on: true, note: "G1", accent: true, slide: false },
      { on: true, note: "D#5", accent: true, slide: false },
      { on: true, note: "A#3", accent: false, slide: false },
      { on: true, note: "C4", accent: true, slide: false },
      { on: true, note: "A#5", accent: false, slide: false },
      { on: true, note: "D4", accent: true, slide: false },
      { on: true, note: "G2", accent: false, slide: false },
      { on: true, note: "G1", accent: false, slide: false },
      { on: true, note: "G1", accent: true, slide: false },
      { on: true, note: "D#5", accent: true, slide: false },
      { on: true, note: "A#3", accent: false, slide: false },
      { on: true, note: "C4", accent: true, slide: false },
      { on: true, note: "A#5", accent: false, slide: false },
      { on: true, note: "D4", accent: true, slide: false },
      { on: true, note: "G2", accent: false, slide: false },
    ],
  },
  {
    id: "sub-zero-bender",
    title: "Sub Zero Bender",
    file: "02-sub-zero-bender.mid",
    bpm: 140,
    range: "C1-A#5",
    pattern: [
      { on: true, note: "A#5", accent: false, slide: false },
      { on: true, note: "C1", accent: false, slide: false },
      { on: true, note: "C2", accent: true, slide: false },
      { on: true, note: "C2", accent: true, slide: true },
      { on: true, note: "A#2", accent: false, slide: false },
      { on: true, note: "D1", accent: false, slide: false },
      { on: true, note: "D5", accent: true, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: true, note: "A#5", accent: false, slide: false },
      { on: true, note: "C1", accent: false, slide: false },
      { on: true, note: "C2", accent: true, slide: false },
      { on: true, note: "C2", accent: true, slide: true },
      { on: true, note: "A#2", accent: false, slide: false },
      { on: true, note: "D1", accent: false, slide: false },
      { on: true, note: "D5", accent: true, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
    ],
  },
  {
    id: "circuit-crawl",
    title: "Circuit Crawl",
    file: "03-circuit-crawl.mid",
    bpm: 140,
    range: "C2-C4",
    pattern: [
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C4", accent: true, slide: true },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C3", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: true, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C4", accent: false, slide: true },
      { on: true, note: "C3", accent: false, slide: true },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
    ],
  },
  {
    id: "pressure-drop",
    title: "Pressure Drop",
    file: "04-pressure-drop.mid",
    bpm: 140,
    range: "C2-C4",
    pattern: [
      { on: true, note: "C2", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C4", accent: true, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: true, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C4", accent: false, slide: true },
      { on: true, note: "C2", accent: false, slide: true },
      { on: true, note: "C3", accent: true, slide: true },
      { on: true, note: "C2", accent: false, slide: true },
    ],
  },
  {
    id: "acid-ratchet",
    title: "Acid Ratchet",
    file: "05-acid-ratchet.mid",
    bpm: 140,
    range: "C2-C4",
    pattern: [
      { on: true, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: true, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: true, slide: true },
      { on: true, note: "C3", accent: true, slide: false },
      { on: true, note: "C2", accent: true, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C4", accent: false, slide: true },
      { on: true, note: "C2", accent: false, slide: true },
      { on: true, note: "C3", accent: false, slide: true },
      { on: true, note: "C2", accent: false, slide: true },
    ],
  },
  {
    id: "chrome-stepper",
    title: "Chrome Stepper",
    file: "06-chrome-stepper.mid",
    bpm: 140,
    range: "C2-C4",
    pattern: [
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C3", accent: false, slide: true },
      { on: true, note: "C2", accent: false, slide: true },
      { on: true, note: "C3", accent: true, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: true, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C4", accent: true, slide: true },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C3", accent: false, slide: true },
    ],
  },
  {
    id: "two-note-panic",
    title: "Two Note Panic",
    file: "07-two-note-panic.mid",
    bpm: 140,
    range: "C2-C3",
    pattern: [
      { on: true, note: "C2", accent: false, slide: true },
      { on: true, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: true },
      { on: true, note: "C3", accent: true, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C3", accent: false, slide: true },
      { on: true, note: "C2", accent: false, slide: true },
      { on: true, note: "C3", accent: true, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C3", accent: false, slide: true },
      { on: true, note: "C2", accent: false, slide: true },
      { on: true, note: "C3", accent: true, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
    ],
  },
  {
    id: "highwire-acid",
    title: "Highwire Acid",
    file: "08-highwire-acid.mid",
    bpm: 140,
    range: "C2-C4",
    pattern: [
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C4", accent: true, slide: true },
      { on: true, note: "C3", accent: false, slide: true },
      { on: true, note: "C2", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C3", accent: true, slide: true },
      { on: true, note: "C2", accent: true, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
    ],
  },
  {
    id: "sub-basement",
    title: "Sub Basement",
    file: "09-sub-basement.mid",
    bpm: 140,
    range: "C1-C3",
    pattern: [
      { on: true, note: "C2", accent: true, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C3", accent: true, slide: true },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C1", accent: true, slide: true },
      { on: true, note: "C2", accent: false, slide: true },
      { on: true, note: "C3", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: true, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
    ],
  },
  {
    id: "minimal-spark",
    title: "Minimal Spark",
    file: "10-minimal-spark.mid",
    bpm: 140,
    range: "C2-C4",
    pattern: [
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C3", accent: true, slide: true },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: true, note: "C4", accent: false, slide: true },
      { on: true, note: "C2", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
      { on: false, note: "C3", accent: false, slide: false },
    ],
  },
];

export const MIDI_PATTERN_MAP = Object.fromEntries(
  MIDI_PATTERNS.map((pattern) => [pattern.id, pattern]),
);
